name: CI
on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

env:
  EXTENSION_TESTER_VERSION: '0.1.1-nao2'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Download test tools
        run: |
          wget -O extension-tester.jar \
            https://github.com/noaione/shosetsu-ext-tester/releases/download/v$EXTENSION_TESTER_VERSION/extension-tester.jar
      - name: Test all extensions
        run: |
          python3 ci/multi-test.py \
            --print-listings \
            --print-list-stats \
            --print-novels \
            --print-meta \
            --test-all-novels \
            --ignore-missing
